# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v20.1.7'
  hooks:
  - id: clang-format
    types_or:
      - "c"
      - "c++"
      - "json"

- repo: https://github.com/maxwinterstein/shfmt-py
  rev: v3.11.0.2
  hooks:
    - id: shfmt
      args: ["-w", "-i", "4", "-ci"]

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    exclude: '^auxil/.*$'

- repo: https://github.com/crate-ci/typos
  rev: v1.16.21
  hooks:
    - id: typos
      exclude: '^(.typos.toml|src/SmithWaterman.cc|testing/.*|auxil/.*|scripts/base/frameworks/files/magic/.*|CHANGES)$'
